export type RuntimeType = 'boolean'
    | 'number'
    | 'string'
    | 'error'
    | 'date'
    | 'regexp'
    | 'function'
    | 'symbol'
    | 'array'
    | 'object'
    | 'map'
    | 'set'
    | 'null'
    | 'undefined';