import { defineAsyncComponent } from 'vue'

export const pagesComponent = {
  "/": defineAsyncComponent(() => import(/* webpackChunkName: "v-8daa1a0e" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/README.vue")),
  "/api-docs/": defineAsyncComponent(() => import(/* webpackChunkName: "v-b858e5f0" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/README.vue")),
  "/guide/": defineAsyncComponent(() => import(/* webpackChunkName: "v-fffb8e28" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/guide/README.vue")),
  "/guide/getting-started.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-fb0f0066" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/guide/getting-started.vue")),
  "/plugins/": defineAsyncComponent(() => import(/* webpackChunkName: "v-67d16688" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/plugins/README.vue")),
  "/plugins/devtools.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-3957e7aa" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/plugins/devtools.vue")),
  "/api-docs/classes/_harlem_core.eventemitter.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-49e8d1a8" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/classes/_harlem_core.eventemitter.vue")),
  "/api-docs/classes/_harlem_core.store.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-2818a111" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/classes/_harlem_core.store.vue")),
  "/api-docs/modules/_harlem_core.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-8d1b77f6" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/modules/_harlem_core.vue")),
  "/api-docs/modules/_harlem_plugin_devtools.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-bbb08d48" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/modules/_harlem_plugin_devtools.vue")),
  "/api-docs/modules/_harlem_plugin_reset.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-784ec1e1" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/modules/_harlem_plugin_reset.vue")),
  "/api-docs/modules/_harlem_plugin_snapshot.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-1906ed84" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/modules/_harlem_plugin_snapshot.vue")),
  "/api-docs/modules/_harlem_plugin_ssr.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-4d6a1684" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/modules/_harlem_plugin_ssr.vue")),
  "/api-docs/modules/_harlem_plugin_storage.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-1fa39675" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/modules/_harlem_plugin_storage.vue")),
  "/api-docs/modules/_harlem_plugin_transaction.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-052a5872" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/modules/_harlem_plugin_transaction.vue")),
  "/api-docs/modules/_harlem_utilities.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-100ef8f8" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/modules/_harlem_utilities.vue")),
  "/api-docs/interfaces/_harlem_core.emittable.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-7821471b" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/interfaces/_harlem_core.emittable.vue")),
  "/api-docs/interfaces/_harlem_core.eventlistener.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-a7f129f0" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/interfaces/_harlem_core.eventlistener.vue")),
  "/api-docs/interfaces/_harlem_core.eventpayload.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-074b3148" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/interfaces/_harlem_core.eventpayload.vue")),
  "/api-docs/interfaces/_harlem_core.harlemplugin.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-3544a36e" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/interfaces/_harlem_core.harlemplugin.vue")),
  "/api-docs/interfaces/_harlem_core.internalstore.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-63241c5c" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/interfaces/_harlem_core.internalstore.vue")),
  "/api-docs/interfaces/_harlem_core.mutationeventdata.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-3600058a" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/interfaces/_harlem_core.mutationeventdata.vue")),
  "/api-docs/interfaces/_harlem_core.options.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-36954578" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/interfaces/_harlem_core.options.vue")),
  "/api-docs/interfaces/_harlem_core.store-1.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-2c06b231" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/interfaces/_harlem_core.store-1.vue")),
  "/api-docs/interfaces/_harlem_core.storebase.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-aacd93b8" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/interfaces/_harlem_core.storebase.vue")),
  "/api-docs/interfaces/_harlem_plugin_devtools.options.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-31b5a3a9" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/interfaces/_harlem_plugin_devtools.options.vue")),
  "/api-docs/interfaces/_harlem_plugin_snapshot.snapshot.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-68ce99f6" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/interfaces/_harlem_plugin_snapshot.snapshot.vue")),
  "/api-docs/interfaces/_harlem_plugin_storage.options.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-3ef61828" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/interfaces/_harlem_plugin_storage.options.vue")),
  "/api-docs/interfaces/_harlem_plugin_transaction.transactioneventdata.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-54150a09" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/api-docs/interfaces/_harlem_plugin_transaction.transactioneventdata.vue")),
  "/404.html": defineAsyncComponent(() => import(/* webpackChunkName: "v-3706649a" */"/Users/andrew/Projects/harlem/app/src/.vuepress/.temp/pages/404.html.vue")),
}
